version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - /home/ubuntu/certbot/www:/var/www/certbot  # This maps the Certbot webroot to Nginx
      - /home/ubuntu/certbot/conf:/etc/letsencrypt # Optional: Maps the Certbot configuration if 
    depends_on:
      - app
#    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

