version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/certbot/www:/var/www/certbot
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
    depends_on:
      - app
#    restart: unless-stopped
  certbot:
    image: certbot/certbot
    volumes:
      - /home/ubuntu/certbot/www:/var/www/certbot
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
#    entrypoint: "certbot certonly --webroot --webroot-path=/var/www/certbot --email wer1915@gmail.com --agree-tos --no-eff-email --staging -d k10b201.p.ssafy.io --rsa-key-size 2048"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx