version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/certbot/www:/var/www/certbot
    depends_on:
      - app
#    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
#    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/certbot/www:/var/www/certbot
    entrypoint: "certbot certonly --webroot --webroot-path=/var/www/certbot --email wer1915@gmail.com --agree-tos --no-eff-email --staging -d k10b201.p.ssafy.io --rsa-key-size 4096 --force-renewal"

