# Use the official Nginx image
FROM nginx:alpine

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy a new configuration file from your project to the container
COPY nginx.conf /etc/nginx/nginx.conf
#COPY nginx.conf /devway/nginx.conf

# Expose port 80
#EXPOSE 80 443

# Start Nginx when the container has provisioned
CMD ["nginx", "-g", "daemon off;"]