# Use the official Nginx image
FROM nginx:alpine

# Remove the default Nginx configuration file

# Copy a new configuration file from your project to the container

# Expose port 80
#EXPOSE 80 443

# Start Nginx when the container has provisioned
CMD ["nginx", "-g", "daemon off;"]